language: php

php:
  - "5.6"
  - "5.5"

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction --no-progress